#server port

server:
  port: 8000
  
spring:
  data:
    mongodb:
       database: local
       host: localhost
       port: 27017
  application:
    name: db-service
       
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000